name: webon_kit_dart
description: A new Flutter package project.
version: 0.0.1
homepage:

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.7

  walletkit_dart:
    path: packages/walletkit-dart
  bip39:
    path: packages/walletkit-dart/packages/bip39
  nomo_ui_kit:
    path: packages/nomo-ui-kit
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0